# import required module
import glob
import os
from collections import OrderedDict
from batchgenerators.utilities.file_and_folder_operations import *
from pathlib import Path
from shutil import copyfile
import nibabel as nib
import scipy.ndimage.interpolation as ip
import numpy as np
# import nnunet

def dataprep(idir,fname,type):
    # predict use nnUNet pretrained
    # os.system('cmd /k "nnUNet_convert_decathlon_task -i /home/qiyuan/Documents/raw/Task03_Liver"')
    # assign directory
    out_directory = os.environ.get('nnUNet_raw_data_base') + '/nnUNet_raw_data/' + fname + '/'
    # Create target Directory if don't exist
    if not os.path.exists(out_directory):
        os.makedirs(out_directory)
        os.makedirs(out_directory + 'imagesTs/')
        os.makedirs(out_directory + 'imagesTr/')
        os.makedirs(out_directory + 'labelsTr/')
        print("Directory ", out_directory, " Created ")

        # iterate over files in
        # that directory
        if type == 'ped':
            i=0
            for filepath in glob.iglob(f'{idir}/*/*/*-CT-*'):  #specially for pediatric dataset
                i = i+1
                head_tail = os.path.split(os.path.normpath(filepath + '/../../'))
                marker = str(i) + '-' + head_tail[1] + '_0000'   #This is the name of nii.gz file
                testdatadir = out_directory + 'imagesTs/'
                os.system('/home/sean/cis2/nnUNet/dcm2niix -f "' + marker + '" -p y -z y -o "' + testdatadir + '" "' + filepath +'"')
        if type == 'nii.gz':
            marker = Path(Path(idir).stem).stem + '_0000.nii.gz'
            copyfile(idir, join(out_directory + 'imagesTs/', marker))
        if type == 'highres':
            data = nib.load(idir)
            img = data.get_fdata()
            scale = 0.5
            img = ip.zoom(img, scale, order=0)
            marker = Path(Path(idir).stem).stem + '_0000.nii.gz'
            data_0 = nib.nifti1.Nifti1Image(img, np.eye(4))
            nib.save(data_0, join(out_directory + 'imagesTs/', marker))
        if type == 'nii.batch':
            for filepath in glob.iglob(f'{idir}/*.nii.gz'):
                head_tail = os.path.split(os.path.normpath(filepath))
                marker = Path(Path(head_tail[1]).stem).stem + '_0000.nii.gz'  # This is the name of $
                copyfile(filepath, join(out_directory + 'imagesTs/', marker))
        if type == 'nii.batch.highres':
            for filepath in glob.iglob(f'{idir}/*.nii.gz'):
                data = nib.load(filepath)
                img = data.get_fdata()
                scale = 0.5
                img = ip.zoom(img, scale, order=0)
                head_tail = os.path.split(os.path.normpath(filepath))
                marker = Path(Path(head_tail[1]).stem).stem + '_0000.nii.gz'  # This is the name of $
                data_0 = nib.nifti1.Nifti1Image(img, np.eye(4))
                nib.save(data_0, join(out_directory + 'imagesTs/', marker))

        # Write into dataset.json
        base = out_directory
        train_folder = join(base, "imagesTr/")
        label_folder = join(base, "labelsTr/")
        test_folder = join(base, "imagesTs/")
        train_patient_names = []
        test_patient_names = []
        train_patients = subfiles(train_folder, join=False, suffix='nii.gz')
        test_patients = subfiles(test_folder, join=False, suffix=".nii.gz")

        json_dict = OrderedDict()
        json_dict['name'] = "generated by QW"
        json_dict['description'] = "-"
        json_dict['tensorImageSize'] = "3D"
        json_dict['reference'] = "-"
        json_dict['licence'] = "-"
        json_dict['release'] = "-"
        json_dict['modality'] = {
            "0": "CT",
        }
        json_dict['labels'] = OrderedDict({
        }
        )
        json_dict['numTraining'] = len(train_patient_names)
        json_dict['numTest'] = len(test_patients)
        json_dict['training'] = [{'image': "./imagesTr/%s" % train_patients, "label": "./labelsTr/%s" % train_patients} for i, train_patients in enumerate(train_patient_names)]
        json_dict['test'] = ["./imagesTs/%s" % test_patients for test_patients in test_patients]

        save_json(json_dict, os.path.join(base, "dataset.json"))

    else:
        print("Directory ", out_directory, " already exists, nothing to be done.")


if __name__ == "__main__":
    input = '/home/sean/torso_mid_result/data'
    foldername = '0430compressed'
    dataprep(input,foldername,'nii.batch.highres')

